class GUI:
    def __init__(self) :
        import tkinter as tk
        import rog7_predict as r7
        window=tk.Tk()
        window.title('ROG PHONE 7 60hz 預測')
        window.geometry('380x400')
        window.resizable(False, False)
        lb1 = tk.Label(text="步數  :   ")
        lb1.grid(row=0, column=0)
        lb1_entry = tk.Entry()
        lb1_entry.insert(0,"50")
        lb1_entry.grid(row=0, column=1)
        lb2=tk.Label(text='CPU 0 使用率:  ')
        lb2.grid(row=1, column=0)
        lb2_entry = tk.Entry(window)
        lb2_entry.insert(0,"100")
        lb2_entry.grid(row=1, column=1)
        lb3=tk.Label(text='CPU 3使用率:  ')
        lb3.grid(row=2, column=0)
        lb3_entry = tk.Entry(window)
        lb3_entry.insert(0,"100")
        lb3_entry.grid(row=2, column=1)
        lb4=tk.Label(text='CPU 7 使用率:  ')
        lb4.grid(row=3, column=0)
        lb4_entry = tk.Entry(window)
        lb4_entry.insert(0,"50")
        lb4_entry.grid(row=3, column=1)
        lb5=tk.Label(text='CPU 0 頻率:  ')
        lb5.grid(row=4, column=0)
        lb5_entry = tk.Entry(window)
        lb5_entry.insert(0,"2016")
        lb5_entry.grid(row=4, column=1)
        lb6=tk.Label(text='CPU 3 頻率:  ')
        lb6.grid(row=5, column=0)
        lb6_entry = tk.Entry(window)
        lb6_entry.insert(0,"2803")
        lb6_entry.grid(row=5, column=1)
        lb7=tk.Label(text='CPU 7 頻率:  ')
        lb7.grid(row=6, column=0)
        lb7_entry = tk.Entry(window)
        lb7_entry.insert(0,"3187")
        lb7_entry.grid(row=6, column=1)
        def output():
            r7.do_task(int(lb1_entry.get()),int(lb2_entry.get()),int(lb3_entry.get()),int(lb4_entry.get()),int(lb5_entry.get()),int(lb6_entry.get()),int(lb7_entry.get()))
        output_btn = tk.Button(text="執行",command=output)
        output_btn.grid(row=7, column=1)
        lb8=tk.Label(text='僅參考用 預測成功率80%')
        lb8.grid(row=8, column=0)
        window.mainloop()

if __name__=="__main__":
    GUI()